NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path("accounts/", include("allauth.urls")),
    path('pages/', include('django.contrib.flatpages.urls')),

]

news/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import NewsList, NewsDetail, NewsSearch, NewsCreate, NewsUpdate, NewsDelete, CategoryListView, subscriptions

urlpatterns = [

   path('', NewsList.as_view(), name='news_list'),
   path('<int:pk>', NewsDetail.as_view(), name='news_detail' ),
   path('search/', NewsSearch.as_view(), name='news_search'),
   path('create/', NewsCreate.as_view(), name='create_news'),
   path('<int:pk>/edit/', NewsUpdate.as_view(), name='news_edit'),
   path('<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
   path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
   path('subscriptions/', subscriptions, name='subscriptions')
]

news/models.py
from django.core.cache import cache
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum("rating"))
        pRat = 0
        pRat += postRat.get("postRating")

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get("commentRating")

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='название')
    users = models.ManyToManyField(User, through='Subscription', blank=True)

    def __str__(self):
        return f'{self.name.title()}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Post(models.Model):

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = "NW"
    ARTICLE = "AR"
    CATEGORY_CHOICES = (
        (NEWS, "Новость"),
        (ARTICLE, "Статья"),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through="PostCategory")
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'new-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return'{}...{}'.format(self.text[0:124] + str(self.rating))


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1032)
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

news/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Exists, OuterRef
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.cache import cache
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_protect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .filters import NewsFilter, NewsForm, PostForm
from .models import Post, Category, Subscription
from datetime import datetime


class NewsList(ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        # С помощью super() мы обращаемся к родительским классам
        # и вызываем у них метод get_context_data с теми же аргументами,
        # что и были переданы нам.
        # В ответе мы должны получить словарь.
        context = super().get_context_data(**kwargs)
        # К словарю добавим текущую дату в ключ 'time_now'.
        context['time_now'] = datetime.utcnow()
        # Добавим ещё одну пустую переменную,
        # чтобы на её примере рассмотреть работу ещё одного фильтра.
        context['next_sale'] = None
        return context


class NewsDetail(DetailView):
    model = Post
    template_name = 'new.html'
    context_object_name = 'new'

    def get_context_data(self, **kwargs):
        # С помощью super() мы обращаемся к родительским классам
        # и вызываем у них метод get_context_data с теми же аргументами,
        # что и были переданы нам.
        # В ответе мы должны получить словарь.
        context = super().get_context_data(**kwargs)
        # К словарю добавим текущую дату в ключ 'time_now'.
        context['time_now'] = datetime.utcnow()
        # Добавим ещё одну пустую переменную,
        # чтобы на её примере рассмотреть работу ещё одного фильтра.
        context['next_sale'] = None
        return context

    queryset = Post.objects.all()

    def get_object(self, *args, **kwargs):  # переопределяем метод получения объекта, как ни странно
        obj = cache.get(f'new-{self.kwargs["pk"]}', None)
        # кэш очень похож на словарь, и метод get действует так же. Он забирает значение по ключу, если его нет, то забирает None.

        # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'new-{self.kwargs["pk"]}', obj)
        return obj


class NewsCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    raise_exception = True
    form_class = PostForm
    model = Post
    template_name = 'create_news.html'


class NewsUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'news_edit.html'


class NewsDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'news_delete.html'
    success_url = reverse_lazy('news_list')


class NewsSearch(ListView):
    model = Post
    template_name = "news_search.html"
    context_object_name = 'news_search'

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = NewsFilter(self.request.GET, queryset)
        # Возвращаем из функции отфильтрованный список товаров
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['time_now'] = datetime.utcnow()
        context['next_sale'] = None
        context['filterset'] = self.filterset
        return context


class CategoryListView(ListView):
    model = Post
    template_name = 'categories.html'
    context_object_name = 'category_list'

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(categoryType=self.category).order_by('-dateCreation')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.category.subscriptions.all()
        context['category'] = self.category
        return context


@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        category = Category.objects.get(id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscription.objects.create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscription.objects.filter(
                user=request.user,
                category=category,
            ).delete()

    categories_with_subscriptions = Category.objects.annotate(
        user_subscribed=Exists(
            Subscription.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('name')
    return render(
        request,
        'subscriptions.html',
        {'categories': categories_with_subscriptions},
    )
# @login_required
# def subscribe(request, pk):
#     user = request.user
#     category = Category.objects.get(id=pk)
#     category.subscribers.add(user)
#     message = 'Вы успешно подписались на рассылку!'

templates/categories.html
{% extends 'flatpages/default.html' %}

{% block title %}
<h1>Подписки по категориям :</h1>
{% endblock title %}

{% block content %}

{% if category.id %}
<div class="Subscription">
    <em>
        Subscription to
    </em>

    <a href="{#% url 'news:Subscription' category.id#}"class="button button-outline">
        Subscription
    </a>
</div>
{% endif %}
{% include "news/inc/posts.html" %}
{% endblock content %}

templates/create_news.html
{% extends 'flatpages/default.html' %}
{% load censor_filter %}
{% block title %}
<h3> Добавте новость:</h3>

{% endblock title %}
{% block content %}
<h1>Добавление новости:</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" > Сохранить </button>
</form>
{% endblock content %}

templates/new.html
{% extends 'flatpages/default.html' %}
{% load censor_filter %}

<!-- Название у нас будет Product -->
{% block title %}
Публикация:
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ new.title|censor }}</h1>
...{{ new.text|censor }}
...{{ new.dateCreation|date:'...  d m Y' }}
...{{new.get_categoryType_display}}
{{new.author.authorUser}}
...{% endblock content %}

templates/new_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> Привет! Вышла новая публикация <a href="{{ link }}">статья</a> в твоем любимом разделе!</h2>
<p>{{ text }}</p>
</body>
</html>

templates/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуйте! Новые статьи за последнюю неделю</h2>
<ul>
  {% for new in news %}
  <li><a href="{{ link }}{{ new.get_absolute_url }}">{{ new.title }}</a> </li>
  {% endfor %}
</ul>

</body>
</html>

templates/news.html
{% extends 'flatpages/default.html' %}

{% load censor_filter %}
{% load custom_tags %}

{% block title %}
<tr><h3> Всего News = {{ news|length }}</h3></tr>
{% endblock title %}

{% block content %}
    <h1>...Все публикации...</h1>

    <h3>Сегодня: {{ time_now|date:'d m Y' }}</h3>
    <a href="{% url 'subscriptions' %}"><h3>Подписаться(жми сюда)</h3></a>

    <form action="" method="get">
        {{ filterset.form.as_p }}

    <a href="{% url 'news_search'  %}">Поиск публикации:</a>
    </form>

    <hr>

    {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
    {% if perms.news.add_post %}
    <a href="{% url 'create_news'  %}">Добавить публикацию</a>
    {% endif %}
    <hr>
   {% if news %}
       <table>
           <tr>
               <td>Заголовки:   </td>
               <td>Тексты:  </td>
               <td>Дата публикации:</td>
               <td>Вид публикации:</td>
               <td>Категория публикации:</td>
               <td>Автор публикации:</td>
               <td>Рейтинг</td>
           </tr>

                {# Условие получается составным. #}
                {% if perms.news.change_post or perms.news.delete_post %}
                <td>Действия</td>
                {% endif %}

          {% for new in object_list %}
           <tr>
               <!-- Не забываем, что переменные в шаблоне ничем не отличаются
                от переменных в Python. Здесь также можно получать доступ к
                полям объекта модели. Например, здесь мы выводим имя,
                в следующем столбце описание, и т.д.  -->
               <td>{{ new.title|censor }}</td>
               <td>{{ new.text|truncatechars:20|censor  }}</td>
               <td>..{{ new.dateCreation|date:'...  d m Y' }}</td>
               <td>.....{{new.get_categoryType_display}}</td>
               < <td>
                        {% for cat in new.postCategory.all%}
                            {{ cat.name }}
                        {% endfor %}
                    </td>
               <td>...{{new.author.authorUser}}</td>
               <td>....{{new.rating }}</td>
           </tr>

                <td>
                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if perms.news.change_post %}
                    <a href="{% url 'news_edit' pk=new.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a href="{% url 'news_delete' new.id %}">Удалить</a>
                    {% endif %}
                </td>

            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>Новых постов пока нет(</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title}}""{{ object.text}}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Режим редактирования</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endblock content %}

templates/news_search.html
{% extends 'flatpages/default.html' %}
{% load censor_filter %}
{% block title %}
Новости
{% endblock title %}

{% block content %}
   <h1>Поиск по:</h1>

   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   {% if news_search %}
       <table>
           <tr>
              <td>Заголовки:   </td>
               <td>Тексты:  </td>
               <td>Дата публикации:</td>
               <td>Вид публикации:</td>
               <td>Категория публикации:</td>
               <td>Автор публикации:</td>
               <td>Рейтинг</td>>


           </tr>

           {% for new in news_search %}
           <tr>
              <td>{{ new.title|censor }}</td>
               <td>{{ new.text|truncatechars:20|censor  }}</td>
               <td>..{{ new.dateCreation|date:'...  d m Y' }}</td>
               <td>.....{{new.get_categoryType_display}}</td>
               < <td>
                        {% for cat in new.postCategory.all%}
                            {{ cat.name }}
                        {% endfor %}
                    </td>
               <td>...{{new.author.authorUser}}</td>
                <td>....{{new.rating }}</td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>таких публикаций нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
<h1>Подписки по категориям :</h1>
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}